<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find sr_description)/urdf/inertials.xacro" />
<xacro:include filename="$(find sr_description)/urdf/materials.xacro" />

<!-- Wheel Joint and Link definition MACRO -->
<xacro:macro name="wheel" params="name radius width mass dx dy">
  <link name="${name}_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${radius}" length="${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <cylinder radius="${radius}" length="${width}"/>
      </geometry>
      <material name="wheel"/>
    </visual>

    <xacro:cylinder_inertial mass="${mass}" radius="${radius}" length="${width}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:cylinder_inertial>
  </link>

  <joint name="${name}_joint" type="continuous">
    <parent link="${robot_name}/base_footprint"/>
    <child link="${name}_link"/>
    <origin xyz="${dx} ${dy} ${wheel_radius}" rpy="${-PI/2.0} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10000" velocity="20.0" />
    <dynamics damping="0" friction="00"/>

  </joint>

  <transmission name="${name}_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_act">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</xacro:macro>

<!-- Chassis Joint and Link definition MACRO -->
<xacro:macro name="chassis" params="name lenght width height axle_offset clearence mass">
  <link name="${name}_link">
    <collision>
      <origin xyz="${-axle_offset} 0 ${height/2.0 + clearence}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenght} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-axle_offset} 0 ${height/2.0 + clearence}" rpy="0 0 0"/>
      <geometry>
        <box size="${lenght} ${width} ${height}"/>
      </geometry>
      <material name="chassis"/>
    </visual>

    <xacro:box_inertial mass="${mass}" x="${lenght}" y="${width}" z="${height}">
      <origin xyz="${-axle_offset} 0 ${height/2.0 + clearence}" rpy="0 0 0" />
    </xacro:box_inertial>
  </link>

  <joint name="${name}_joint" type="fixed">
    <parent link="${robot_name}/base_footprint"/>
    <child link="${name}_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>


</xacro:macro>

<!-- Caster wheel joint and Link definition MACRO -->
<xacro:macro name="caster" params="name radius mass offset dx">
  <link name="${name}_rotation_link">
    <collision>
      <origin xyz="${-offset/2.0} 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${offset} ${radius} ${radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-offset/2.0} 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${offset} ${radius} ${radius}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <xacro:box_inertial mass="${mass/10.0}" x="${offset}" y="${radius}" z="${radius}">
      <origin xyz="${-offset/2.0} 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
  </link>

  <joint name="${name}_rotation_joint" type="continuous">
    <parent link="${robot_name}/base_footprint"/>
    <child link="${name}_rotation_link"/>
    <origin xyz="${dx} 0 ${1.5*caster_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.01" friction="0.1"/>
  </joint>

  <link name="${name}_wheel_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry>
      <material name="wheel"/>
    </visual>

    <xacro:sphere_inertial mass="${9.0/10.0*mass}" radius="${radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:sphere_inertial>
  </link>

  <joint name="${name}_wheel_joint" type="continuous">
    <parent link="${name}_rotation_link"/>
    <child link="${name}_wheel_link"/>
    <origin xyz="${-offset} 0 ${-caster_radius / 2.0}" rpy="${-PI/2.0} 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.01" friction="1.5"/>
  </joint>

</xacro:macro>

</robot>
